# scripts/generate_data_yaml.py
"""
One-time script: converts scripts/district_centroids_raw.csv into
configs/data.yaml per master doc §7 schema.
Applies known GADM -> current-official-name renames explicitly,
rather than silently trusting the source data's naming.
"""

import pandas as pd
import yaml

INPUT_CSV = "scripts/district_centroids_raw.csv"
OUTPUT_YAML = "configs/data.yaml"

# Confirmed renames: GADM's NAME_2 -> current official district name
# Source: UP cabinet decisions, verified via web search 2026-07-19
RENAME_MAP = {
    "Allahabad": "Prayagraj",
    "Faizabad": "Ayodhya",
    "Sant Ravi Das Nagar": "Bhadohi",
}

def to_district_id(name: str) -> str:
    """Normalize a district name into a config-safe id: lowercase, underscores."""
    return name.strip().lower().replace(" ", "_")

df = pd.read_csv(INPUT_CSV)

assert len(df) == 75, f"Expected 75 districts, got {len(df)} — do not proceed."

df["district_name_current"] = df["district_name"].replace(RENAME_MAP)
df["district_id"] = df["district_name_current"].apply(to_district_id)

# Check for duplicate ids (would indicate a naming collision)
dupes = df[df.duplicated("district_id", keep=False)]
if not dupes.empty:
    print("WARNING: duplicate district_id found:")
    print(dupes)
    raise SystemExit("Fix duplicates before generating YAML.")

districts = []
for _, row in df.iterrows():
    districts.append({
        "district_id": row["district_id"],
        "district_name": row["district_name_current"],
        "lat": round(float(row["lat"]), 6),
        "lon": round(float(row["lon"]), 6),
    })

config = {
    "districts": districts,
    "date_range": {
        "start": "1984-01-01",
        "end": "2025-12-31",
    },
    "nasa_power": {
        "community": "AG",
        "parameters": [
            "T2M_MAX", "T2M_MIN", "RH2M", "WS10M", "WD10M",
            "PRECTOTCORR", "PS", "ALLSKY_SFC_SW_DWN", "CLRSKY_SFC_SW_DWN",
            "CLOUD_AMT", "GWETROOT", "GWETTOP",
        ],
        "fill_value": -999,
        "max_retries": 5,
        "backoff_base_seconds": 2,
    },
    "missing_value_policy": {
        "interpolation_max_gap_days": 3,
    },
}

with open(OUTPUT_YAML, "w") as f:
    f.write("# Auto-generated by scripts/generate_data_yaml.py\n")
    f.write("# District centroids: GADM 4.1 admin level 2, reprojected via EPSG:7755\n")
    f.write("# 3 districts renamed from GADM source to current official names:\n")
    for old, new in RENAME_MAP.items():
        f.write(f"#   {old} -> {new}\n")
    f.write("\n")
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)

print(f"Wrote {len(districts)} districts to {OUTPUT_YAML}")